### ISSUE TITLE
Exception when running on OS X

### ISSUE THREAD

**Issue by egorzhdan** [maheshhingane/BoyerMoore#1]
I get this error every time when try to run on Mac:

Checking file:  .DS_Store
Traceback (most recent call last):
  File "BoyerMoore.py", line 29, in <module>
    pattern_file = ''.join(open(sys.argv[2]).readlines())

Mac OS X stores .DS_Store system file in every directory, so this file should not be processed by the program

**Comment by maheshhingane** [comment]
Thanks egorzhdan for pointing the issue out. This was a class project that was supposed to be run on my  university's linux server, so this issue was not encountered earlier. I will make the corresponding changes to the code to handle this.
